# Generated by Django 4.2 on 2024-02-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_order',
        ),
    ]
